version: '3.8'
services:
    php:
      container_name: 'cbr-php'
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
        args:
          tz: '${TIMEZONE:-Europe/Moscow}'
      volumes:
        - './:/var/www/'
        - './docker/php/docker.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      ports:
        - '${APP_PORT:-80}:80'
      command: ["php", "artisan", "serve", '--host=0.0.0.0', '--port=80']
      environment:
          PHP_IDE_CONFIG: 'serverName=CBR'
      depends_on:
        - database
      networks:
        - cbr

    database:
      container_name: 'cbr-pgsql'
      image: 'postgres:14'
      ports:
        - '${DB_FORWARD_PORT:-5432}:${DB_PORT}'
      environment:
        POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        POSTGRES_DB: '${DB_DATABASE:-default}'
        POSTGRES_USER: '${DB_USERNAME:-postgres}'
        TZ: '${TIMEZONE}'
      volumes:
        - 'panels-db:/var/lib/postgresql/data:rw'
      networks:
        - cbr

    swagger:
        container_name: 'cbr-swagger'
        image: 'swaggerapi/swagger-ui'
        ports:
          - "${SWAGGER_PORT:-8000}:8080"
        volumes:
          - './swagger.json:/usr/share/nginx/html/swagger.json'
        environment:
          API_URL: swagger.json
        networks:
          - cbr

    redis:
        container_name: 'cbr-redis'
        image: 'redis:latest'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        networks:
            - cbr

volumes:
  panels-db:
    driver: local

networks:
  cbr:
    driver: bridge
